apiVersion: v2
name: contextify
description: A Helm chart for deploying contextify web and server components on Kubernetes
type: application
version: 0.1.5
appVersion: "1.0.0"
home: https://github.com/devplaninc/contextify
sources:
  - https://github.com/devplaninc/contextify
maintainers:
  - name: DevPlan Inc
    email: info@devplan.com
keywords:
  - contextify
  - development
  - observer
kubeVersion: ">=1.19.0"
dependencies: []